name: zaben-checkmk tests
on: [push]
jobs:
  validate_lint_check_rubocop-Ruby_2-5-7-Puppet_6:
    runs-on: ruby:2.5.7
    env:
      PUPPET_GEM_VERSION: '~> 6'
    steps:
      - uses: ./.github/before_script
      - name: Run validate lint check rubocop
        run: bundle exec rake validate lint check rubocop
  parallel_spec-Ruby_2-5-7-Puppet_6:
    runs-on: ruby:2.5.7
    needs: [validate_lint_check_rubocop-Ruby_2-5-7-Puppet_6]
    env:
      PUPPET_GEM_VERSION: '~> 6'
    steps:
      - uses: ./.github/before_script
      - name: Run parallel_spec
        run: bundle exec rake parallel_spec
  validate_lint_check_rubocop-Ruby_2-7-2-Puppet_7:
    runs-on: ruby:2.7.2
    env:
      PUPPET_GEM_VERSION: '~> 7'
    steps:
      - uses: ./.github/before_script
      - name: Run validate lint check rubocop
        run: bundle exec rake validate lint check rubocop
  parallel_spec-Ruby_2-7-2-Puppet_7:
    runs-on: ruby:2.7.2
    needs: [validate_lint_check_rubocop-Ruby_2-7-2-Puppet_7]
    env:
      PUPPET_GEM_VERSION: '~> 7'
    steps:
      - uses: ./.github/before_script
      - name: Run parallel_spec
        run: bundle exec rake parallel_spec
