name: zaben-checkmk tests
on: [push]
jobs:
  before_script:
    name: before script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: before script
        run: |
          bundle -v
          rm Gemfile.lock || true
          "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
          "# Set `rubygems_version` in the .sync.yml to set a value"
          "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
          '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
          gem --version
  validate_lint_check_rubocop-Ruby_2.5.7-Puppet_~>_6:
    runs-on: ruby:2.5.7
    env:
      PUPPET_GEM_VERSION: '~> 6'
    steps:
      - uses: ./.github/before_script
      - name: Run validate lint check rubocop
        run: bundle exec rake validate lint check rubocop
  parallel_spec-Ruby_2.5.7-Puppet_~>_6:
    runs-on: ruby:2.5.7
    needs: [validate_lint_check_rubocop-Ruby_2.5.7-Puppet_~>_6]
    env:
      PUPPET_GEM_VERSION: '~> 6'
    steps:
      - uses: ./.github/before_script
      - name: Run parallel_spec
        run: bundle exec rake parallel_spec
  validate_lint_check_rubocop-Ruby_2.7.2-Puppet_~>_7:
    runs-on: ruby:2.7.2
    env:
      PUPPET_GEM_VERSION: '~> 7'
    steps:
      - uses: ./.github/before_script
      - name: Run validate lint check rubocop
        run: bundle exec rake validate lint check rubocop
  parallel_spec-Ruby_2.7.2-Puppet_~>_7:
    runs-on: ruby:2.7.2
    needs: [validate_lint_check_rubocop-Ruby_2.7.2-Puppet_~>_7]
    env:
      PUPPET_GEM_VERSION: '~> 7'
    steps:
      - uses: ./.github/before_script
      - name: Run parallel_spec
        run: bundle exec rake parallel_spec
